## Basic operation in Tensorflow

Tensor Creation:

tf.constant(): Create constant tensors
Syntax: tf.constant(value, dtype=None, shape=None, name='Const')


tf.Variable(): Create mutable tensors that can be updated during training therefore used for the model parameters.
Syntax: tf.Variable(initial_value, name=None, dtype=None)


tf.zeros(), tf.ones(): Create tensors filled with 0s or 1s


tf.random.normal(): Create tensors with random values drawn from a normal distribution.


In [ ]:
import tensorflow as tf

# Ensure TensorFlow 2.x behavior
tf.compat.v1.enable_eager_execution()

# 1. tf.constant(): Create constant tensors
const_tensor = tf.constant(5.0, dtype=tf.float32)
print("Constant Tensor:", const_tensor.numpy())

# 2. tf.Variable(): Create mutable tensors
var_tensor = tf.Variable(5.0, dtype=tf.float32)
print("Variable Tensor:", var_tensor.numpy())

# 3. tf.zeros(), tf.ones(): Create tensors filled with 0s or 1s
zeros_tensor = tf.zeros([3, 3], dtype=tf.float32)
ones_tensor = tf.ones([3, 3], dtype=tf.float32)
print("Zeros Tensor:", zeros_tensor.numpy())
print("Ones Tensor:", ones_tensor.numpy())

# 4. tf.random.normal(): Create tensors with random values
random_tensor = tf.random.normal([3, 3], mean=0.0, stddev=1.0, dtype=tf.float32)
print("Random Normal Tensor:", random_tensor.numpy())


Constant Tensor: 5.0
Variable Tensor: 5.0
Zeros Tensor: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Tensor: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Random Normal Tensor: [[ 0.7046776  -0.23545773  0.64569485]
 [ 0.17530797  1.4227375   0.16837333]
 [-0.3455063   0.5465385  -0.20086426]]


## Mathematical Operations:

Addition: tf.add() or '+'


Subtraction: tf.subtract() or '-'


Multiplication: tf.multiply() or '*'


Division: tf.divide() or '/'


Matrix multiplication: tf.matmul()


In [ ]:
import tensorflow as tf

# Ensure TensorFlow 2.x behavior
tf.compat.v1.enable_eager_execution()

# Define tensors
a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# a) Addition
add_result_1 = tf.add(a, b)
add_result_2 = a + b  # Alternative way
print("Addition (tf.add):\n", add_result_1.numpy())
print("Addition (+):\n", add_result_2.numpy())

# b) Subtraction
sub_result_1 = tf.subtract(a, b)
sub_result_2 = a - b  # Alternative way
print("Subtraction (tf.subtract):\n", sub_result_1.numpy())
print("Subtraction (-):\n", sub_result_2.numpy())

# c) Multiplication (element-wise)
mul_result_1 = tf.multiply(a, b)
mul_result_2 = a * b  # Alternative way
print("Multiplication (tf.multiply):\n", mul_result_1.numpy())
print("Multiplication (*):\n", mul_result_2.numpy())

# d) Division (element-wise)
div_result_1 = tf.divide(a, b)
div_result_2 = a / b  # Alternative way
print("Division (tf.divide):\n", div_result_1.numpy())
print("Division (/):\n", div_result_2.numpy())

# e) Matrix multiplication
matmul_result = tf.matmul(a, b)
print("Matrix Multiplication (tf.matmul):\n", matmul_result.numpy())


Addition (tf.add):
 [[ 6.  8.]
 [10. 12.]]
Addition (+):
 [[ 6.  8.]
 [10. 12.]]
Subtraction (tf.subtract):
 [[-4. -4.]
 [-4. -4.]]
Subtraction (-):
 [[-4. -4.]
 [-4. -4.]]
Multiplication (tf.multiply):
 [[ 5. 12.]
 [21. 32.]]
Multiplication (*):
 [[ 5. 12.]
 [21. 32.]]
Division (tf.divide):
 [[0.2        0.33333334]
 [0.42857143 0.5       ]]
Division (/):
 [[0.2        0.33333334]
 [0.42857143 0.5       ]]
Matrix Multiplication (tf.matmul):
 [[19. 22.]
 [43. 50.]]


##Tensor Manipulation:

Reshaping: tf.reshape()


Transposing: tf.transpose()


Concatenation: tf.concat()


Slicing: tensor[start:end]


In [ ]:
import tensorflow as tf

# Ensure TensorFlow 2.x behavior
tf.compat.v1.enable_eager_execution()

# Define a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
print("Original Tensor:\n", tensor.numpy())

# a) Reshaping: tf.reshape()
reshaped_tensor = tf.reshape(tensor, [3, 2])
print("Reshaped Tensor (2x3 to 3x2):\n", reshaped_tensor.numpy())

# b) Transposing: tf.transpose()
transposed_tensor = tf.transpose(tensor)
print("Transposed Tensor:\n", transposed_tensor.numpy())

# c) Concatenation: tf.concat()
tensor_a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensor_b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
concatenated_tensor = tf.concat([tensor_a, tensor_b], axis=0)  # Concatenate along rows
print("Concatenated Tensor along rows:\n", concatenated_tensor.numpy())

concatenated_tensor_1 = tf.concat([tensor_a, tensor_b], axis=1)  # Concatenate along columns
print("Concatenated Tensor along columns:\n", concatenated_tensor_1.numpy())

# d) Slicing: tensor[start:end]
sliced_tensor = tensor[0:1, 1:3]  # Slice second row and second and third columns
print("Sliced Tensor (first row, second and third columns):\n", sliced_tensor.numpy())


Original Tensor:
 [[1. 2. 3.]
 [4. 5. 6.]]
Reshaped Tensor (2x3 to 3x2):
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
Transposed Tensor:
 [[1. 4.]
 [2. 5.]
 [3. 6.]]
Concatenated Tensor along rows:
 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
Concatenated Tensor along columns:
 [[1. 2. 5. 6.]
 [3. 4. 7. 8.]]
Sliced Tensor (first row, second and third columns):
 [[2. 3.]]


##TensorFlow Data Types

a) Numeric Types:
- tf.float32, tf.float64: Floating-point numbers
- tf.int8, tf.int16, tf.int32, tf.int64: Signed integers
- tf.uint8, tf.uint16: Unsigned integers
- tf.bool: Boolean values

b) String Type:
- tf.string: For text data

c) Complex Number Types:
- tf.complex64, tf.complex128: Complex numbers

d) Quantized Types:
- tf.qint8, tf.quint8, tf.qint32: For quantized operations


In [ ]:
import tensorflow as tf

# a) Numeric Types:
# Floating-point numbers
float32_tensor = tf.constant(3.14, dtype=tf.float32)
float64_tensor = tf.constant(3.14, dtype=tf.float64)

# Signed integers
int8_tensor = tf.constant(127, dtype=tf.int8)
int16_tensor = tf.constant(32767, dtype=tf.int16)
int32_tensor = tf.constant(2147483647, dtype=tf.int32)
int64_tensor = tf.constant(9223372036854775807, dtype=tf.int64)

# Unsigned integers
uint8_tensor = tf.constant(255, dtype=tf.uint8)
uint16_tensor = tf.constant(65535, dtype=tf.uint16)

# Boolean
bool_tensor = tf.constant(True, dtype=tf.bool)

# b) String Type:
string_tensor = tf.constant("Hello, TensorFlow!", dtype=tf.string)

# c) Complex Number Types:
complex64_tensor = tf.constant(1 + 2j, dtype=tf.complex64)
complex128_tensor = tf.constant(1 + 2j, dtype=tf.complex128)

# d) Quantized Types:
# These are typically used in specific quantization contexts
qint8_tensor = tf.quantization.quantize(tf.constant([-1.0, 0.0, 1.0]), -1.0, 1.0, tf.qint8)
quint8_tensor = tf.quantization.quantize(tf.constant([0.0, 1.0, 2.0]), 0.0, 2.0, tf.quint8)
qint32_tensor = tf.quantization.quantize(tf.constant([-1.0, 0.0, 1.0]), -1.0, 1.0, tf.qint32)

# Print out the tensors to see their values and types
print("float32:", float32_tensor)
print("float64:", float64_tensor)
print("int8:", int8_tensor)
print("int16:", int16_tensor)
print("int32:", int32_tensor)
print("int64:", int64_tensor)
print("uint8:", uint8_tensor)
print("uint16:", uint16_tensor)
print("bool:", bool_tensor)
print("string:", string_tensor)
print("complex64:", complex64_tensor)
print("complex128:", complex128_tensor)
print("qint8:", qint8_tensor)
print("quint8:", quint8_tensor)
print("qint32:", qint32_tensor)

Instructions for updating:
`tf.quantize_v2` is deprecated, please use `tf.quantization.quantize` instead.


float32: tf.Tensor(3.14, shape=(), dtype=float32)
float64: tf.Tensor(3.14, shape=(), dtype=float64)
int8: tf.Tensor(127, shape=(), dtype=int8)
int16: tf.Tensor(32767, shape=(), dtype=int16)
int32: tf.Tensor(2147483647, shape=(), dtype=int32)
int64: tf.Tensor(9223372036854775807, shape=(), dtype=int64)
uint8: tf.Tensor(255, shape=(), dtype=uint8)
uint16: tf.Tensor(65535, shape=(), dtype=uint16)
bool: tf.Tensor(True, shape=(), dtype=bool)
string: tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)
complex64: tf.Tensor((1+2j), shape=(), dtype=complex64)
complex128: tf.Tensor((1+2j), shape=(), dtype=complex128)
qint8: QuantizeV2(output=<tf.Tensor: shape=(3,), dtype=qint8, numpy=array([-128,   -1,  127], dtype=int8)>, output_min=<tf.Tensor: shape=(), dtype=float32, numpy=-1.0>, output_max=<tf.Tensor: shape=(), dtype=float32, numpy=1.0>)
quint8: QuantizeV2(output=<tf.Tensor: shape=(3,), dtype=quint8, numpy=array([  0, 128, 255], dtype=uint8)>, output_min=<tf.Tensor: shape=(), dtype=floa

##Creating and manipulating matrices in TensorFlow

Creating Matrices: Define matrices using tf.constant().

Matrix Addition: Use tf.add() or the + operator.

Element-wise Multiplication: Use tf.multiply() or the * operator.

Matrix Multiplication (Dot Product): Use tf.matmul().

Matrix Transpose: Use tf.transpose().


In [ ]:
import tensorflow as tf

# Creating matrices
matrix_a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
matrix_b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
print("Matrix A:\n", matrix_a.numpy())
print("Matrix B:\n", matrix_b.numpy())

# Matrix addition
matrix_add = tf.add(matrix_a, matrix_b)
print("Matrix Addition:\n", matrix_add.numpy())

# Matrix multiplication (element-wise)
matrix_mul_elementwise = tf.multiply(matrix_a, matrix_b)
print("Element-wise Multiplication:\n", matrix_mul_elementwise.numpy())

# Matrix multiplication (dot product)
matrix_mul = tf.matmul(matrix_a, matrix_b)
print("Matrix Multiplication (dot product):\n", matrix_mul.numpy())

# Matrix transpose
matrix_transpose = tf.transpose(matrix_a)
print("Matrix Transpose:\n", matrix_transpose.numpy())


Matrix A:
 [[1. 2.]
 [3. 4.]]
Matrix B:
 [[5. 6.]
 [7. 8.]]
Matrix Addition:
 [[ 6.  8.]
 [10. 12.]]
Element-wise Multiplication:
 [[ 5. 12.]
 [21. 32.]]
Matrix Multiplication (dot product):
 [[19. 22.]
 [43. 50.]]
Matrix Transpose:
 [[1. 3.]
 [2. 4.]]


Creating Matrices: Define matrices using tf.constant().

Matrix Addition: Use tf.add() or the + operator.

Element-wise Multiplication: Use tf.multiply() or the * operator.

Matrix Multiplication (Dot Product): Use tf.matmul().

Matrix Transpose: Use tf.transpose().

## Defining Operations in TensorFlow

Defining a Simple Function: Use standard Python function definition to create operations. In TensorFlow 2.x, these are executed eagerly by default.


Using tf.function for Performance Optimization:
- Decorate functions with @tf.function to compile them into a static graph for faster execution.
- tf.function improves performance by optimizing and parallelizing the execution of operations.


In [ ]:
import tensorflow as tf

# Define a simple function
def simple_operation(a, b):
    return tf.add(a, b)

# Using tf.function for performance optimization
@tf.function
def optimized_operation(a, b):
    return tf.add(a, b)

# Sample inputs
a = tf.constant(10)
b = tf.constant(20)

# Execute operations
result_simple = simple_operation(a, b)
result_optimized = optimized_operation(a, b)

print("Simple Operation Result:", result_simple.numpy())
print("Optimized Operation Result:", result_optimized.numpy())


Simple Operation Result: 30
Optimized Operation Result: 30


##Layering Nested Operations
Creating Complex Operations by Nesting Functions

In [ ]:
import tensorflow as tf

# Define nested functions
def add_and_multiply(a, b):
    add_result = tf.add(a, b)
    mul_result = tf.multiply(a, b)
    return add_result, mul_result

# Higher-level function that uses the nested function
def complex_operation(x, y, z):
    add_mul_result = add_and_multiply(x, y)
    final_result = tf.subtract(add_mul_result[0], z)
    return final_result

# Sample inputs
x = tf.constant(5)
y = tf.constant(3)
z = tf.constant(2)

# Execute the complex operation
result = complex_operation(x, y, z)
print("Complex Operation Result:", result.numpy())


Complex Operation Result: 6


Nested Functions: Create reusable operations by nesting functions.

Higher-Level Functions: Organize code by using higher-level functions that call nested functions.

Best Practices for Organizing Code:

Modularity: Break down complex operations into smaller, reusable functions.

Readability: Use meaningful function names and comments to improve code readability.

Maintainability: Organize functions logically to make the code easier to maintain and extend.

## Building and Executing Computational Graphs in TensorFlow
TensorFlow allows you to build and execute computational graphs. With TensorFlow 2.x, eager execution is enabled by default, making it easier to develop and debug models. However, you can still build and execute static computational graphs using @tf.function for performance optimization. Here’s a detailed look at both approaches:

In [ ]:
import tensorflow as tf

# Define a simple operation with eager execution (dynamic graph)
def simple_operation(a, b):
    return tf.add(a, b)

# Define the same operation with @tf.function for static graph execution
@tf.function
def optimized_operation(a, b):
    return tf.add(a, b)

# Sample inputs
a = tf.constant(10)
b = tf.constant(20)

# Execute operations
result_simple = simple_operation(a, b)
result_optimized = optimized_operation(a, b)

print("Simple Operation Result:", result_simple.numpy())         # Eager execution
print("Optimized Operation Result:", result_optimized.numpy())   # Static graph execution


1. Eager Execution (Dynamic Graphs)
Eager execution allows operations to be executed immediately, providing a more intuitive and interactive way to build and test your models.



In [ ]:
import tensorflow as tf

# Enable eager execution (default in TensorFlow 2.x)
print("Eager execution:", tf.executing_eagerly())

# Define tensors
a = tf.constant(2.0)
b = tf.constant(3.0)

# Perform operations
c = a + b
d = a * b

# Print results
print("Addition result (eager execution):", c.numpy())
print("Multiplication result (eager execution):", d.numpy())


Eager execution: True
Addition result (eager execution): 5.0
Multiplication result (eager execution): 6.0


2. Static Graphs (Using @tf.function)
Static graphs allow TensorFlow to optimize and parallelize the execution of operations, improving performance for repeated executions.

Example: Static Graph Execution with @tf.function

In [ ]:
import tensorflow as tf

# Define a function using tf.function to create a static graph
@tf.function
def compute_operations(a, b):
    c = tf.add(a, b)
    d = tf.multiply(a, b)
    return c, d

# Define tensors
a = tf.constant(2.0)
b = tf.constant(3.0)

# Execute operations
c, d = compute_operations(a, b)

# Print results
print("Addition result (static graph):", c.numpy())
print("Multiplication result (static graph):", d.numpy())


Addition result (static graph): 5.0
Multiplication result (static graph): 6.0


##Activation Functions


Activation functions are mathematical functions used in neural networks to introduce non-linearity into the model. They are a critical component because they enable neural networks to learn and represent complex patterns. Without activation functions, a neural network would simply be a linear regression model, regardless of the number of layers.


In [ ]:
import tensorflow as tf

# Ensure TensorFlow 2.x behavior
tf.compat.v1.enable_eager_execution()

# Define a sample tensor
tensor = tf.constant([-1.0, 0.0, 1.0], dtype=tf.float32)
print("Original Tensor:\n", tensor.numpy())

# a) ReLU (Rectified Linear Unit): tf.nn.relu()
relu_tensor = tf.nn.relu(tensor)
print("ReLU Applied:\n", relu_tensor.numpy())

# b) Sigmoid: tf.nn.sigmoid()
sigmoid_tensor = tf.nn.sigmoid(tensor)
print("Sigmoid Applied:\n", sigmoid_tensor.numpy())

# c) Tanh (Hyperbolic Tangent): tf.nn.tanh()
tanh_tensor = tf.nn.tanh(tensor)
print("Tanh Applied:\n", tanh_tensor.numpy())


Original Tensor:
 [-1.  0.  1.]
ReLU Applied:
 [0. 0. 1.]
Sigmoid Applied:
 [0.26894143 0.5        0.7310586 ]
Tanh Applied:
 [-0.7615942  0.         0.7615942]


## Building Neural Networks with Multiple Layers



In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Define a simple neural network model
model = models.Sequential([
    layers.Dense(32, activation='relu', input_shape=(64,)),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# Print the model summary
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                2080      
                                                                 
 dense_1 (Dense)             (None, 64)                2112      
                                                                 
 dense_2 (Dense)             (None, 10)                650       
                                                                 
Total params: 4842 (18.91 KB)
Trainable params: 4842 (18.91 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


Explanation:

Sequential API: Use tf.keras.Sequential to stack layers in a linear manner.

Dense Layers: Define fully connected layers with tf.keras.layers.Dense.

###Using tf.keras to Simplify Layer Management

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Define a more complex model
model = models.Sequential()

# Adding layers incrementally
model.add(layers.Dense(32, activation='relu', input_shape=(64,)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

# Print the model summary
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 32)                2080      
                                                                 
 dense_4 (Dense)             (None, 64)                2112      
                                                                 
 dense_5 (Dense)             (None, 10)                650       
                                                                 
Total params: 4842 (18.91 KB)
Trainable params: 4842 (18.91 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


Explanation:

- Layer Management: Add layers incrementally to a tf.keras.Sequential model.
- Model Summary: Use model.summary() to display the model architecture and parameters.

Key Points:
- Layering Nested Operations: Create complex operations by nesting functions and organizing code for readability and maintainability.
- Working with Multiple Layers: Build neural networks with multiple layers using tf.keras, leveraging the Sequential API to simplify layer management.

## Implementing Loss Functions

Common Loss Functions

MSE

In [ ]:
import tensorflow as tf

# Example usage of MSE
y_true = tf.constant([1.0, 2.0, 3.0])
y_pred = tf.constant([1.1, 2.1, 2.9])
mse = tf.keras.losses.MeanSquaredError()
loss = mse(y_true, y_pred)
print("MSE Loss:", loss.numpy())


MSE Loss: 0.009999989


Categorical Cross-Entropy

In [ ]:
import tensorflow as tf

# Example usage of Categorical Cross-Entropy
y_true = tf.constant([[0, 1, 0], [0, 0, 1]])
y_pred = tf.constant([[0.05, 0.95, 0.0], [0.1, 0.8, 0.1]])
cce = tf.keras.losses.CategoricalCrossentropy()
loss = cce(y_true, y_pred)
print("Categorical Cross-Entropy Loss:", loss.numpy())


Categorical Cross-Entropy Loss: 1.1769392


Implementing Custom Loss Functions

In [ ]:
import tensorflow as tf

# Custom loss function
def custom_loss_function(y_true, y_pred):
    return tf.reduce_mean(tf.abs(y_true - y_pred))

# Example usage of custom loss function
y_true = tf.constant([1.0, 2.0, 3.0])
y_pred = tf.constant([1.1, 2.1, 2.9])
loss = custom_loss_function(y_true, y_pred)
print("Custom Loss:", loss.numpy())


Custom Loss: 0.09999994


Explanation:

Mean Squared Error (MSE): Measures the average squared difference between the predicted and actual values.

Categorical Cross-Entropy: Measures the difference between two probability distributions for classification tasks.

Custom Loss Functions: Define a custom loss function by creating a function that takes true labels and predictions as input and returns a scalar loss value.